# frozen_string_literal: true

require_relative "test_helper"

class JSONToSQLTest < SiloMigrateTest
  USERS_JSON = <<~JSON
    {
      "object_name": "users",
      "total_records": 2,
      "data": [
        {
          "id": "user:1",
          "uid": 1,
          "score": 1,
          "login": "alice",
          "banned": false,
          "email": null,
          "createdAt": "2024-01-02T03:04:05Z",
          "avatar": {"url": "https://example.com/a.png"},
          "replies": {"totalCount": 3},
          "tags": {"edges": [
            {"node": {"id": "tag:1", "text": "one"}},
            {"node": {"id": "tag:2", "text": "two"}}
          ]},
          "ssoFields": ["terms", "privacy"]
        },
        {
          "id": "user:2",
          "uid": 2,
          "score": 2.5,
          "login": "bob",
          "banned": true,
          "email": "bob@example.com",
          "createdAt": "2024-02-03T04:05:06+02:00",
          "avatar": {"url": "https://example.com/b.png"},
          "replies": {"totalCount": 0},
          "tags": {"edges": []},
          "ssoFields": []
        }
      ]
    }
  JSON

  def convert(input, output, **options)
    converter = SiloMigrate::JSONToSQLConverter.new(verbose: false, **options)
    stats = converter.convert(Pathname(input), Pathname(output))
    [stats, File.read(output)]
  end

  def test_converts_envelope_file_with_flattening_and_child_tables
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")
      stats, sql = convert(input, output)

      assert_includes sql, "-- Generated by json-to-sql converter"
      assert_includes sql, "SET NAMES utf8mb4;"
      assert_includes sql, "SET FOREIGN_KEY_CHECKS = 0;"
      assert_match(/SET FOREIGN_KEY_CHECKS = 1;\nSET UNIQUE_CHECKS = 1;\n\z/, sql)

      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "`_sid` BIGINT NOT NULL"
      assert_includes sql, "PRIMARY KEY (`_sid`)"
      assert_includes sql, "`id` VARCHAR(255) NOT NULL"
      assert_includes sql, "KEY `idx_id` (`id`)"
      assert_includes sql, "`uid` BIGINT NOT NULL"
      assert_includes sql, "`score` DOUBLE NOT NULL"
      assert_includes sql, "`banned` TINYINT(1) NOT NULL"
      assert_includes sql, "`email` VARCHAR(255),"
      assert_includes sql, "`created_at` DATETIME NOT NULL"
      assert_includes sql, "`avatar_url` VARCHAR(255) NOT NULL"
      assert_includes sql, "`replies_total_count` BIGINT NOT NULL"

      assert_includes sql, "CREATE TABLE `users_tags`"
      assert_includes sql, "`_parent_sid` BIGINT NOT NULL"
      assert_includes sql, "`_parent_id` VARCHAR(255)"
      assert_includes sql, "`_ordinal` BIGINT NOT NULL"
      assert_includes sql, "KEY `idx_parent_sid` (`_parent_sid`)"
      assert_includes sql, "KEY `idx_parent_id` (`_parent_id`)"

      assert_includes sql, "CREATE TABLE `users_sso_fields`"
      assert_includes sql, "`value` VARCHAR(255) NOT NULL"

      # Root rows: NULL email for alice, UTC-normalized datetime for bob.
      assert_includes sql, "(1, 'user:1', 1, 1, 'alice', 0, NULL, '2024-01-02 03:04:05', 'https://example.com/a.png', 3)"
      assert_includes sql, "(2, 'user:2', 2, 2.5, 'bob', 1, 'bob@example.com', '2024-02-03 02:05:06', 'https://example.com/b.png', 0)"

      # Child rows carry synthetic + natural parent keys and 0-based ordinals.
      assert_includes sql, "(1, 1, 'user:1', 0, 'tag:1', 'one')"
      assert_includes sql, "(2, 1, 'user:1', 1, 'tag:2', 'two')"
      assert_includes sql, "(1, 1, 'user:1', 0, 'terms')"
      assert_includes sql, "(2, 1, 'user:1', 1, 'privacy')"

      assert_equal 3, stats[:tables_processed]
      assert_equal 2, stats[:rows_processed]
      assert_equal 4, stats[:child_rows_processed]
      assert_equal 1, stats[:files_processed]
    end
  end

  def test_natural_parent_id_falls_back_to_first_id_suffixed_scalar
    json = <<~JSON
      {
        "object_name": "kudos",
        "total_records": 1,
        "data": [
          {
            "message_id": "message:9",
            "kudos": {"edges": [
              {"node": {"weight": 1, "user": {"user_id": "user:1", "user_login": "al"}}}
            ]}
          }
        ]
      }
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "kudos.json"), json)
      output = File.join(dir, "kudos.sql")
      _, sql = convert(input, output)

      assert_includes sql, "CREATE TABLE `kudos_kudos`"
      assert_includes sql, "`user_user_id` VARCHAR(255) NOT NULL"
      assert_includes sql, "`user_user_login` VARCHAR(255) NOT NULL"
      assert_includes sql, "(1, 1, 'message:9', 0, 1, 'user:1', 'al')"
    end
  end

  def test_top_level_array_uses_file_basename_and_table_override
    json = '[{"a": 1}, {"a": 2}]'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "My-Events.json"), json)
      output = File.join(dir, "out.sql")
      stats, sql = convert(input, output)
      assert_includes sql, "CREATE TABLE `my_events`"
      assert_equal 2, stats[:rows_processed]

      _, sql = convert(input, File.join(dir, "out2.sql"), table_name: "events")
      assert_includes sql, "CREATE TABLE `events`"
    end
  end

  def test_keeping_graphql_wrappers_when_unwrap_disabled
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")
      _, sql = convert(input, output, graphql_unwrap: false)

      assert_includes sql, "CREATE TABLE `users_tags_edges`"
      assert_includes sql, "`node_id` VARCHAR(255) NOT NULL"
      assert_includes sql, "`node_text` VARCHAR(255) NOT NULL"
      refute_includes sql, "CREATE TABLE `users_tags`\n"
    end
  end

  def test_type_widening_to_string_and_text_tiers
    rows = [
      { "mixed" => 1, "big" => "x" * 300, "absent" => "here" },
      { "mixed" => "two", "big" => "y" }
    ]
    json = Oj.dump({ "object_name" => "things", "total_records" => 2, "data" => rows }, mode: :compat)

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "things.json"), json)
      output = File.join(dir, "things.sql")
      _, sql = convert(input, output)

      assert_includes sql, "`mixed` VARCHAR(255) NOT NULL"
      assert_includes sql, "`big` TEXT NOT NULL"
      # Field missing from one record must be nullable.
      assert_includes sql, "`absent` VARCHAR(255),"
      # Integer in a string-widened column is emitted as its quoted string form.
      assert_includes sql, "(1, '1', '#{'x' * 300}', 'here')"
      assert_includes sql, "(2, 'two', 'y', NULL)"
    end
  end

  def test_wide_inferred_table_promotes_varchars_to_text
    row = { "id" => "message:1" }
    80.times { |index| row["field_#{index}"] = "value-#{index}" }
    json = Oj.dump({ "object_name" => "messages", "data" => [row] }, mode: :compat)

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "messages.json"), json)
      output = File.join(dir, "messages.sql")
      snapshots = []
      stats = SiloMigrate::JSONToSQLConverter.new(verbose: false).convert(
        Pathname(input),
        Pathname(output),
        progress_callback: proc { |snapshot| snapshots << snapshot },
        progress_interval: 0
      )
      sql = File.read(output)

      assert_includes sql, "ENGINE=InnoDB ROW_FORMAT=DYNAMIC"
      assert_includes sql, "`id` VARCHAR(255) NOT NULL"
      assert_includes sql, "KEY `idx_id` (`id`)"
      assert_operator sql.scan(/`field_\d+` TEXT NOT NULL/).length, :>, 0
      assert_equal 1, stats[:warnings].length
      assert_includes stats[:warnings].first, "messages: estimated utf8mb4 row width"
      assert_includes stats[:warnings].first, "promoted"
      assert_includes stats[:warnings].first, "VARCHAR columns to TEXT"
      warning = snapshots.find { |snapshot| snapshot[:event] == :warning }
      refute_nil warning
      assert_includes warning[:message], "messages: estimated utf8mb4 row width"
    end
  end

  def test_row_size_limiter_accounts_for_child_metadata
    defs = 62.times.map do |index|
      SiloMigrate::JSONToSQL::ColumnDef.new(name: "field_#{index}", kind: :string, sql_type: "VARCHAR(255)", null: false)
    end
    limiter = SiloMigrate::JSONToSQL::RowSizeLimiter.new

    root = limiter.fit(defs, child: false)
    child = limiter.fit(defs, child: true)

    assert_empty root.promoted
    assert_equal 1, child.promoted.length
    assert_operator child.estimated_after, :<=, SiloMigrate::JSONToSQL::RowSizeLimiter::MAX_ROW_BYTES
    assert defs.all? { |column| column.sql_type == "VARCHAR(255)" }, "limiter must not mutate source definitions"
  end

  def test_wide_schema_driven_table_is_row_size_limited
    properties = { "id" => { "type" => "string", "maxLength" => 255 } }
    row = { "id" => "record:1" }
    70.times do |index|
      properties["field_#{index}"] = { "type" => "string", "maxLength" => 255 }
      row["field_#{index}"] = "value-#{index}"
    end
    schema = Oj.dump(
      {
        "type" => "object",
        "properties" => {
          "object_name" => { "type" => "string", "const" => "wide_records" },
          "data" => { "type" => "array", "items" => { "type" => "object", "properties" => properties } }
        }
      },
      mode: :compat
    )
    json = Oj.dump({ "object_name" => "wide_records", "data" => [row] }, mode: :compat)

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "wide_records.schema.json"), schema)
      input = write(File.join(dir, "wide_records.json"), json)
      stats, sql = convert(input, File.join(dir, "wide_records.sql"), schema_dir: schema_dir)

      assert_includes sql, "`id` VARCHAR(255)"
      assert_operator sql.scan(/`field_\d+` TEXT/).length, :>, 0
      assert_includes stats[:warnings].first, "wide_records: estimated utf8mb4 row width"
    end
  end

  def test_batching_splits_inserts
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")
      _, sql = convert(input, output, batch_size: 1)

      assert_equal 2, sql.scan("INSERT INTO `users` ").length
      assert_equal 2, sql.scan("INSERT INTO `users_tags` ").length
    end
  end

  def test_rejects_non_positive_batch_size
    error = assert_raises(SiloMigrate::UsageError) do
      SiloMigrate::JSONToSQLConverter.new(batch_size: 0, verbose: false)
    end

    assert_includes error.message, "JSON batch size must be greater than 0"
  end

  def test_json_fallback_for_deep_nesting_mixed_arrays_and_forced_paths
    json = <<~JSON
      {"object_name": "deep", "data": [
        {
          "a": {"b": {"c": {"d": 1}}},
          "mixed": [1, {"x": 2}],
          "keep": {"raw": true}
        }
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "deep.json"), json)
      output = File.join(dir, "deep.sql")
      stats, sql = convert(input, output, max_depth: 3, json_columns: ["keep"])

      assert_includes sql, "`a_b_c_json` LONGTEXT NOT NULL"
      assert_includes sql, "`mixed_json` LONGTEXT NOT NULL"
      assert_includes sql, "`keep_json` LONGTEXT NOT NULL"
      assert_includes sql, %q{'{"d":1}'}
      assert_includes sql, %q{'[1,{"x":2}]'}
      assert_includes sql, %q{'{"raw":true}'}
      assert_equal 3, stats[:json_fallback_columns]
    end
  end

  def test_column_collisions_get_suffixes_and_long_names_are_truncated
    long_key = "x" * 80
    json = Oj.dump(
      { "object_name" => "weird", "data" => [{ "a" => { "b" => 1 }, "a_b" => 2, long_key => 3 }] },
      mode: :compat
    )

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "weird.json"), json)
      output = File.join(dir, "weird.sql")
      stats, sql = convert(input, output)

      assert_includes sql, "`a_b` BIGINT NOT NULL"
      assert_includes sql, "`a_b_2` BIGINT NOT NULL"
      assert_equal 1, stats[:column_collisions]
      truncated = sql[/`(x{55}_\h{8})`/, 1]
      refute_nil truncated, "expected a hash-truncated column name for the 80-char key"
      assert_equal 64, truncated.length
    end
  end

  def test_heterogeneous_field_shapes_produce_both_columns
    json = <<~JSON
      {"object_name": "posts", "data": [
        {"id": "post:1", "plusOne": null},
        {"id": "post:2", "plusOne": {"count": 3}}
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "posts.json"), json)
      output = File.join(dir, "posts.sql")
      _, sql = convert(input, output)

      assert_includes sql, "`plus_one` VARCHAR(255),"
      assert_includes sql, "`plus_one_count` BIGINT,"
      assert_includes sql, "(1, 'post:1', NULL, NULL)"
      assert_includes sql, "(2, 'post:2', NULL, 3)"
    end
  end

  def test_gzip_input_output_schema_only_and_file_filters
    Dir.mktmpdir do |dir|
      gzip_write(File.join(dir, "users.json.gz"), USERS_JSON)
      gzip_write(File.join(dir, "skipme.json.gz"), USERS_JSON.gsub('"users"', '"members"'))
      output = File.join(dir, "out.sql.gz")
      snapshots = []
      stats = SiloMigrate::JSONToSQLConverter.new(include_files: ["users"], schema_only: true, verbose: false).convert(
        Pathname(dir),
        Pathname(output),
        progress_callback: proc { |snapshot| snapshots << snapshot },
        progress_interval: 0
      )
      sql = Zlib::GzipReader.open(output, &:read)

      assert_equal 1, stats[:files_processed]
      assert_equal 1, stats[:files_skipped]
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "CREATE TABLE `users_tags`"
      refute_includes sql, "INSERT INTO"
      refute_includes sql, "CREATE TABLE `members`"
      assert_equal :start, snapshots.first[:event]
      assert_equal :complete, snapshots.last[:event]
      assert snapshots.any? { |snapshot| snapshot[:event] == :bytes && snapshot[:current_file][:bytes_read].positive? }
      assert snapshots.any? { |snapshot| snapshot[:current_file]&.fetch(:name) == "users.json.gz" }
    end
  end

  def test_empty_jsonl_file_is_skipped_without_aborting_other_files
    Dir.mktmpdir do |dir|
      write(File.join(dir, "boards.jsonl"), "")
      write(File.join(dir, "accounts.json"), USERS_JSON)
      output = File.join(dir, "out.sql")
      snapshots = []

      stats = SiloMigrate::JSONToSQLConverter.new(verbose: false).convert(
        Pathname(dir),
        Pathname(output),
        progress_callback: proc { |snapshot| snapshots << snapshot },
        progress_interval: 0
      )
      sql = File.read(output)

      assert_equal 1, stats[:files_processed]
      assert_equal 1, stats[:files_skipped]
      assert_equal ["boards.jsonl is empty and will be skipped"], stats[:warnings]
      assert_includes sql, "CREATE TABLE `users`"
      refute_includes sql, "CREATE TABLE `boards`"

      warning = snapshots.find { |snapshot| snapshot[:event] == :warning }
      refute_nil warning, "expected a :warning progress event"
      assert_equal "boards.jsonl is empty and will be skipped", warning[:message]
      assert_nil snapshots.last[:current_file]
    end
  end

  def test_excluding_root_table_excludes_children_and_child_exclusion_is_targeted
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)

      _, sql = convert(input, File.join(dir, "a.sql"), exclude_tables: ["users"])
      refute_includes sql, "CREATE TABLE"

      stats, sql = convert(input, File.join(dir, "b.sql"), exclude_tables: ["users_tags"])
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "CREATE TABLE `users_sso_fields`"
      refute_includes sql, "CREATE TABLE `users_tags`"
      refute_includes sql, "INSERT INTO `users_tags`"
      assert_equal 1, stats[:tables_skipped]

      _, sql = convert(input, File.join(dir, "c.sql"), include_tables: ["users"])
      assert_includes sql, "CREATE TABLE `users_tags`"
    end
  end

  def test_envelope_without_object_name_uses_basename_and_records_path
    json = '{"data": [{"id": "role:1", "name": "Admin"}]}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "role_users.json"), json)
      _, sql = convert(input, File.join(dir, "a.sql"))
      assert_includes sql, "CREATE TABLE `role_users`"

      custom = write(File.join(dir, "custom.json"), '{"items": [{"a": 1}], "data": "not records"}')
      _, sql = convert(custom, File.join(dir, "b.sql"), records_path: "items")
      assert_includes sql, "CREATE TABLE `custom`"
      assert_includes sql, "`a` BIGINT NOT NULL"

      error = assert_raises(SiloMigrate::UsageError) do
        convert(custom, File.join(dir, "c.sql"), records_path: "missing")
      end
      assert_includes error.message, "records path 'missing'"
    end
  end

  def test_sole_non_data_array_key_is_used_as_records_in_auto_mode
    json = '{"object_name": "tags", "items": [{"t": "x"}, {"t": "y"}]}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "tags.json"), json)
      stats, sql = convert(input, File.join(dir, "tags.sql"))

      assert_includes sql, "CREATE TABLE `tags`"
      assert_equal 2, stats[:rows_processed]
    end
  end

  def test_duplicate_table_names_across_files_raise
    Dir.mktmpdir do |dir|
      write(File.join(dir, "one.json"), '{"object_name": "users", "data": [{"a": 1}]}')
      write(File.join(dir, "two.json"), '{"object_name": "users", "data": [{"a": 2}]}')

      error = assert_raises(SiloMigrate::UsageError) do
        convert(dir, File.join(dir, "out.sql"))
      end
      assert_includes error.message, "Table name 'users' is produced by both"
    end
  end

  def test_atomic_conversion_renames_temp_output_after_success
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")
      convert(input, output)

      assert File.exist?(output)
      refute File.exist?("#{output}.tmp")
    end
  end

  def test_atomic_conversion_preserves_existing_output_after_failure
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "bad.json"), '{"object_name": "users", "data": [{"a": 1},')
      output = File.join(dir, "out.sql")
      write(output, "existing output\n")

      assert_raises(SiloMigrate::UsageError) do
        convert(input, output)
      end

      assert_equal "existing output\n", File.read(output)
      refute File.exist?("#{output}.tmp")
    end
  end

  TRUNCATED_THINGS_JSON = '{"object_name": "things", "total_records": 5, "data": [' \
                          '{"id": "t:1", "n": 1}, {"id": "t:2", "n": 2}, {"id": "t:3", "n": 3}, ' \
                          '{"id": "t:4", "body": "cut off mid stri'

  def test_truncated_file_raises_usage_error_with_truncation_hint
    truncated = USERS_JSON[0, USERS_JSON.index("alice") + 3]

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "messages.json"), truncated)
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "out.sql"))
      end

      assert_includes error.message, "Malformed JSON in messages.json"
      assert_includes error.message, "appears to be truncated"
      assert_includes error.message, "--recover-truncated"
      assert_includes error.message, "--exclude-files messages"
    end
  end

  def test_recover_truncated_keeps_complete_records_and_warns_with_counts
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "things.json"), TRUNCATED_THINGS_JSON)
      output = File.join(dir, "things.sql")
      stats, sql = convert(input, output, recover_truncated: true)

      assert_equal 3, stats[:rows_processed]
      assert_equal 1, stats[:files_recovered]
      assert_includes sql, "'t:3'"
      refute_includes sql, "'t:4'"
      assert_equal 1, stats[:warnings].length
      assert_includes stats[:warnings].first, "things.json is truncated"
      assert_includes stats[:warnings].first, "recovered 3 complete record(s), expected 5"
      assert_includes stats[:warnings].first, "re-export"
    end
  end

  def test_recover_truncated_still_raises_when_nothing_is_salvageable
    Dir.mktmpdir do |dir|
      # Truncated before the first record completes.
      input = write(File.join(dir, "empty.json"), '{"object_name": "empty", "data": [{"id": "cut')
      assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "a.sql"), recover_truncated: true)
      end

      # Structurally malformed but not truncated.
      bad = write(File.join(dir, "bad.json"), '{"object_name": "bad", "data": [}]}')
      assert_raises(SiloMigrate::UsageError) do
        convert(bad, File.join(dir, "b.sql"), recover_truncated: true)
      end
    end
  end

  def test_recover_truncated_works_in_schema_driven_single_pass_mode
    schema = <<~JSON
      {
        "type": "object",
        "properties": {
          "object_name": {"type": "string", "const": "things"},
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["id"],
              "properties": {"id": {"type": "string"}, "n": {"type": "integer"}, "body": {"type": "string"}}
            }
          }
        }
      }
    JSON

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "things.schema.json"), schema)
      input = write(File.join(dir, "things.json"), TRUNCATED_THINGS_JSON)
      stats, sql = convert(input, File.join(dir, "things.sql"), schema_dir: schema_dir, recover_truncated: true)

      assert_equal 3, stats[:rows_processed]
      assert_equal 1, stats[:files_recovered]
      assert_includes sql, "'t:3'"
      assert_includes stats[:warnings].first, "recovered 3 complete record(s)"
    end
  end

  def test_complete_but_invalid_file_raises_usage_error_without_truncation_hint
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "bad.json"), '{"object_name": "users", "data": [{"a": 1},]}')
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "out.sql"))
      end

      assert_includes error.message, "Malformed JSON in bad.json"
      refute_includes error.message, "appears to be truncated"
    end
  end

  def test_warnings_are_emitted_as_progress_events_and_collected_in_stats
    json = '{"object_name": "users", "total_records": 5, "data": [{"a": 1}]}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      snapshots = []
      stats = SiloMigrate::JSONToSQLConverter.new(verbose: false).convert(
        Pathname(input),
        Pathname(File.join(dir, "users.sql")),
        progress_callback: proc { |snapshot| snapshots << snapshot },
        progress_interval: 0
      )

      warning = snapshots.find { |snapshot| snapshot[:event] == :warning }
      refute_nil warning, "expected a :warning progress event"
      assert_includes warning[:message], "total_records says 5 but 1"
      assert_equal 1, stats[:warnings].length
      assert_includes stats[:warnings].first, "total_records says 5 but 1"
    end
  end

  def test_conversion_does_not_slurp_json_with_file_read
    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")
      file_singleton = class << File; self; end
      verbose = $VERBOSE
      $VERBOSE = nil
      file_singleton.alias_method :read_without_json_stream_test, :read
      file_singleton.define_method(:read) do |*args|
        raise "JSON conversion must stream input instead of using File.read" if args.first.to_s.end_with?(".json")

        read_without_json_stream_test(*args)
      end
      $VERBOSE = verbose

      convert(input, output)
    ensure
      if file_singleton&.method_defined?(:read_without_json_stream_test)
        verbose = $VERBOSE
        $VERBOSE = nil
        file_singleton.alias_method :read, :read_without_json_stream_test
        file_singleton.remove_method :read_without_json_stream_test
        $VERBOSE = verbose
      end
    end
  end

  def test_streaming_smoke_with_many_records
    Dir.mktmpdir do |dir|
      input = File.join(dir, "posts.json")
      File.open(input, "w") do |file|
        file.write('{"object_name": "posts", "total_records": 50000, "data": [')
        50_000.times do |index|
          file.write(",") if index.positive?
          file.write(%({"id": "post:#{index}", "n": #{index}, "tags": {"edges": [{"node": {"t": "tag#{index % 7}"}}]}}))
        end
        file.write("]}")
      end
      output = File.join(dir, "posts.sql")
      snapshots = []

      stats = SiloMigrate::JSONToSQLConverter.new(verbose: false).convert(
        Pathname(input),
        Pathname(output),
        progress_callback: proc { |snapshot| snapshots << snapshot },
        progress_interval: 0
      )

      assert_equal 50_000, stats[:rows_processed]
      assert_equal 50_000, stats[:child_rows_processed]
      assert snapshots.any? { |snapshot| snapshot[:event] == :bytes && snapshot[:current_file][:bytes_read].positive? }
      assert snapshots.any? { |snapshot| snapshot[:event] == :rows }
      assert_includes File.read(output, 2000), "CREATE TABLE `posts`"
    end
  end

  USERS_SCHEMA = <<~JSON
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Users",
      "type": "object",
      "required": ["data", "object_name"],
      "properties": {
        "object_name": {"type": "string", "const": "users"},
        "total_records": {"type": "integer"},
        "data": {"type": "array", "items": {"$ref": "#/definitions/User"}}
      },
      "definitions": {
        "User": {
          "type": "object",
          "required": ["id", "login", "banned", "registrationTime", "status", "avatar"],
          "properties": {
            "id": {"type": "string"},
            "login": {"type": "string", "x-pii": true, "x-pii-note": "Username"},
            "email": {"type": ["string", "null"], "format": "email", "x-pii": true},
            "banned": {"type": "boolean"},
            "score": {"type": "number"},
            "registrationTime": {"type": "string", "format": "date-time"},
            "status": {"type": "string", "enum": ["FULLY_REGISTERED", "PENDING"]},
            "plusOne": {"type": ["object", "null"]},
            "avatar": {
              "type": "object",
              "required": ["url"],
              "properties": {"url": {"type": "string", "maxLength": 100}}
            },
            "badges": {
              "type": "object",
              "required": ["edges"],
              "properties": {
                "edges": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": ["node"],
                    "properties": {"node": {"$ref": "#/definitions/Badge"}}
                  }
                }
              }
            }
          }
        },
        "Badge": {
          "type": "object",
          "required": ["id"],
          "properties": {"id": {"type": "string"}, "title": {"type": "string"}}
        }
      }
    }
  JSON

  SCHEMA_USERS_DATA = <<~JSON
    {"object_name": "users", "total_records": 1, "data": [
      {
        "id": "user:1",
        "login": "alice",
        "email": null,
        "banned": false,
        "score": 1,
        "registrationTime": "2024-01-02T03:04:05Z",
        "status": "PENDING",
        "plusOne": {"who": "knows"},
        "avatar": {"url": "https://example.com/a.png"},
        "badges": {"edges": [{"node": {"id": "badge:1", "title": "First"}}]},
        "notInSchema": "dropped"
      }
    ]}
  JSON

  def test_schema_driven_ddl_with_pii_comments_and_meta_table
    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "users.schema.json"), USERS_SCHEMA)
      input = write(File.join(dir, "users.json"), SCHEMA_USERS_DATA)
      output = File.join(dir, "users.sql")
      stats, sql = convert(input, output, schema_dir: schema_dir)

      # Schema-declared types, not inferred ones.
      assert_includes sql, "`id` TEXT NOT NULL"
      assert_includes sql, "`login` TEXT NOT NULL COMMENT 'x-pii'"
      assert_includes sql, "`email` TEXT COMMENT 'x-pii'"
      assert_includes sql, "`banned` TINYINT(1) NOT NULL"
      assert_includes sql, "`score` DOUBLE,"
      assert_includes sql, "`registration_time` DATETIME NOT NULL"
      assert_includes sql, "`status` VARCHAR(32) NOT NULL"
      assert_includes sql, "`plus_one_json` LONGTEXT,"
      assert_includes sql, "`avatar_url` VARCHAR(100) NOT NULL"
      # TEXT id columns cannot carry a plain KEY in MySQL.
      refute_includes sql, "KEY `idx_id`"

      assert_includes sql, "CREATE TABLE `users_badges`"
      assert_includes sql, "`title` TEXT,"

      # Row emission: schema-typed values, unexpected field dropped.
      assert_includes sql, "(1, 'user:1', 'alice', NULL, 0, 1, '2024-01-02 03:04:05', 'PENDING', '{\"who\":\"knows\"}', 'https://example.com/a.png')"
      assert_includes sql, "(1, 1, 'user:1', 0, 'badge:1', 'First')"
      refute_includes sql, "dropped"
      assert_equal 1, stats[:dropped_values]

      # PII manifest table.
      assert_includes sql, "CREATE TABLE `_json_meta`"
      assert_includes sql, "('users', 'login', 'login', 1, 'Username', 'users.schema.json')"
      assert_includes sql, "('users', 'email', 'email', 1, NULL, 'users.schema.json')"
    end
  end

  def test_schema_driven_records_path_supports_dot_notation
    schema = <<~JSON
      {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "users": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {"id": {"type": "string"}, "login": {"type": "string"}}
                }
              }
            }
          }
        }
      }
    JSON
    json = '{"data": {"users": [{"id": "u:1", "login": "alice"}]}}'

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "users.schema.json"), schema)
      input = write(File.join(dir, "users.json"), json)
      stats, sql = convert(input, File.join(dir, "users.sql"), schema_dir: schema_dir, records_path: "data.users")

      assert_equal 1, stats[:rows_processed]
      assert_equal 0, stats[:dropped_values]
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "`id` TEXT"
      assert_includes sql, "`login` TEXT"
      assert_includes sql, "(1, 'u:1', 'alice')"
      refute_includes sql, "CREATE TABLE `users_data_users`"
    end
  end

  def test_schema_driven_records_path_config_is_used_for_schema_and_streaming
    schema = <<~JSON
      {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "users": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {"id": {"type": "string"}}
                }
              }
            }
          }
        }
      }
    JSON
    json = '{"data": {"users": [{"id": "u:1"}]}}'

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "users.schema.json"), schema)
      input = write(File.join(dir, "users.json"), json)
      config = write(File.join(dir, "paths.yml"), "users: data.users\n")
      stats, sql = convert(input, File.join(dir, "users.sql"), schema_dir: schema_dir,
                           records_path: "data", records_path_config: config)

      assert_equal 1, stats[:rows_processed]
      assert_equal 0, stats[:dropped_values]
      assert_includes sql, "`id` TEXT"
      assert_includes sql, "(1, 'u:1')"
      refute_includes sql, "CREATE TABLE `users_data_users`"
    end
  end

  def test_schema_driven_relay_unwrap_tolerates_connection_and_edge_siblings
    schema = <<~JSON
      {
        "type": "object",
        "properties": {
          "object_name": {"type": "string", "const": "messages"},
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {"type": "string"},
                "tags": {
                  "type": "object",
                  "properties": {
                    "totalCount": {"type": "integer"},
                    "edges": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "cursor": {"type": "string"},
                          "node": {
                            "type": "object",
                            "properties": {"id": {"type": "string"}, "text": {"type": "string"}}
                          }
                        }
                      }
                    },
                    "pageInfo": {
                      "type": "object",
                      "properties": {"hasNextPage": {"type": "boolean"}}
                    }
                  }
                }
              }
            }
          }
        }
      }
    JSON
    json = <<~JSON
      {"object_name": "messages", "data": [
        {"id": "message:1", "tags": {
          "totalCount": 1,
          "edges": [{"cursor": "abc", "node": {"id": "tag:1", "text": "ruby"}}],
          "pageInfo": {"hasNextPage": false}
        }}
      ]}
    JSON

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "messages.schema.json"), schema)
      input = write(File.join(dir, "messages.json"), json)
      stats, sql = convert(input, File.join(dir, "messages.sql"), schema_dir: schema_dir)

      assert_equal 1, stats[:rows_processed]
      assert_equal 1, stats[:child_rows_processed]
      assert_equal 0, stats[:dropped_values]
      assert_includes sql, "CREATE TABLE `messages_tags`"
      refute_includes sql, "CREATE TABLE `messages_tags_edges`"
      assert_includes sql, "(1, 1, 'message:1', 0, 'tag:1', 'ruby')"
      refute_includes sql, "`cursor`"
      refute_includes sql, "page_info"
      refute_includes sql, "total_count"
    end
  end

  def test_malformed_schema_file_raises_usage_error
    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "users.schema.json"), '{"type": "object", "properties": {')
      input = write(File.join(dir, "users.json"), USERS_JSON)

      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "users.sql"), schema_dir: schema_dir)
      end
      assert_includes error.message, "users.schema.json"
    end
  end

  def test_schema_dir_without_matching_schema_falls_back_to_inference
    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      FileUtils.mkdir_p(schema_dir)
      input = write(File.join(dir, "users.json"), USERS_JSON)
      output = File.join(dir, "users.sql")

      converter = SiloMigrate::JSONToSQLConverter.new(schema_dir: schema_dir, verbose: true)
      stdout, = capture_io { converter.convert(Pathname(input), Pathname(output)) }

      assert_includes stdout, "[WARN] No JSON Schema found for users.json"
      sql = File.read(output)
      assert_includes sql, "CREATE TABLE `users`"
      refute_includes sql, "CREATE TABLE `_json_meta`"
    end
  end

  def test_total_records_mismatch_warns
    json = '{"object_name": "users", "total_records": 5, "data": [{"a": 1}]}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      output = File.join(dir, "users.sql")
      converter = SiloMigrate::JSONToSQLConverter.new(verbose: true)
      stdout, = capture_io { converter.convert(Pathname(input), Pathname(output)) }

      assert_includes stdout, "[WARN] users.json: total_records says 5 but 1 records were found"
    end
  end

  # ---------------------------------------------------------------------------
  # GraphQL / Relay unwrap_edges relaxation (Issues 2 & 3)
  # ---------------------------------------------------------------------------

  def test_unwrap_edges_tolerates_pageinfo_sibling
    # Standard Relay connection: edges + pageInfo alongside each other.
    json = <<~JSON
      {"data": {"users": {"edges": [
        {"node": {"id": "user:1", "login": "alice"}},
        {"node": {"id": "user:2", "login": "bob"}}
      ], "pageInfo": {"hasNextPage": false, "endCursor": null}}}}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      _, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges")

      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "`node_id` VARCHAR(255)"
      assert_includes sql, "`node_login` VARCHAR(255)"
      assert_includes sql, "'user:1'"
      assert_includes sql, "'alice'"
      assert_includes sql, "'user:2'"
      assert_includes sql, "'bob'"
    end
  end

  def test_unwrap_edges_tolerates_pageinfo_on_nested_connection
    # pageInfo alongside edges in a nested sub-object (e.g. tags on a message).
    # Once records are correctly streamed, the Shredder must unwrap nested
    # connections that carry pageInfo siblings.
    json = <<~JSON
      {"object_name": "messages", "total_records": 1, "data": [
        {
          "id": "message:1",
          "subject": "Hello",
          "tags": {
            "edges": [
              {"node": {"id": "tag:1", "text": "ruby"}},
              {"node": {"id": "tag:2", "text": "sql"}}
            ],
            "pageInfo": {"hasNextPage": false, "endCursor": null}
          }
        }
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "messages.json"), json)
      _, sql = convert(input, File.join(dir, "messages.sql"))

      # tags is a child table, not stored as JSON blob
      assert_includes sql, "CREATE TABLE `messages_tags`"
      assert_includes sql, "`id` VARCHAR(255)"
      assert_includes sql, "`text` VARCHAR(255)"
      assert_includes sql, "'tag:1'"
      assert_includes sql, "'ruby'"
      refute_includes sql, "tags_json"
    end
  end

  def test_unwrap_edges_tolerates_cursor_on_edge_objects
    # Relay per-edge cursor: each edge carries cursor + node.
    # The cursor is discarded; only node content is shredded.
    json = <<~JSON
      {"object_name": "bans", "total_records": 2, "data": [
        {"cursor": "abc", "node": {"id": "1", "userId": 100, "bannedReason": "spam"}},
        {"cursor": "def", "node": {"id": "2", "userId": 200, "bannedReason": "crypto"}}
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "bans.json"), json)
      _, sql = convert(input, File.join(dir, "bans.sql"))

      assert_includes sql, "CREATE TABLE `bans`"
      # cursor is a scalar column (from the edge object record)
      assert_includes sql, "`cursor` VARCHAR(255)"
      # node fields are flattened
      assert_includes sql, "`node_id` VARCHAR(255)"
      assert_includes sql, "`node_user_id` BIGINT"
      assert_includes sql, "`node_banned_reason` VARCHAR(255)"
    end
  end

  def test_unwrap_edges_tolerates_cursor_inside_connection
    json = <<~JSON
      {"object_name": "messages", "data": [
        {"id": "message:1", "tags": {"edges": [
          {"cursor": "abc", "node": {"id": "tag:1", "text": "ruby"}}
        ]}}
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "messages.json"), json)
      _, sql = convert(input, File.join(dir, "messages.sql"))

      assert_includes sql, "CREATE TABLE `messages_tags`"
      assert_includes sql, "'tag:1'"
      assert_includes sql, "'ruby'"
      refute_includes sql, "`cursor`"
    end
  end

  def test_unwrap_edges_tolerates_totalcount_sibling
    # totalCount (another common Relay sibling) alongside edges.
    json = <<~JSON
      {"object_name": "badge_sets", "data": [
        {"id": "bs:1", "badges": {
          "totalCount": 3,
          "edges": [
            {"node": {"id": "badge:1", "title": "First"}},
            {"node": {"id": "badge:2", "title": "Second"}}
          ]
        }}
      ]}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "badge_sets.json"), json)
      _, sql = convert(input, File.join(dir, "badge_sets.sql"))

      assert_includes sql, "CREATE TABLE `badge_sets_badges`"
      assert_includes sql, "`id` VARCHAR(255)"
      assert_includes sql, "`title` VARCHAR(255)"
      refute_includes sql, "badges_json"
    end
  end

  # ---------------------------------------------------------------------------
  # RecordStreamer dot-notation records_path (Issue 4)
  # ---------------------------------------------------------------------------

  def test_records_path_two_segments
    json = '{"data": {"users": [{"id": "u:1"}, {"id": "u:2"}]}}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      stats, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.users")

      assert_includes sql, "CREATE TABLE `users`"
      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'u:1'"
      assert_includes sql, "'u:2'"
    end
  end

  def test_records_path_three_segments
    json = '{"data": {"community": {"roles": [{"id": "role:1", "name": "Admin"}, {"id": "role:2", "name": "Member"}]}}}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "roles.json"), json)
      stats, sql = convert(input, File.join(dir, "roles.sql"), records_path: "data.community.roles")

      assert_includes sql, "CREATE TABLE `roles`"
      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'role:1'"
      assert_includes sql, "'Admin'"
    end
  end

  def test_records_path_four_segments_with_relay_envelope
    # data.community.topTags.edges is the path; each edge has cursor+node
    json = <<~JSON
      {"data": {"community": {"topTags": {"edges": [
        {"node": {"id": "tag:1", "text": "ruby", "messagesCount": 42}},
        {"node": {"id": "tag:2", "text": "sql", "messagesCount": 17}}
      ], "pageInfo": {"hasNextPage": false}}}}}
    JSON

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "topTags.json"), json)
      stats, sql = convert(input, File.join(dir, "topTags.sql"), records_path: "data.community.topTags.edges")

      assert_includes sql, "CREATE TABLE `top_tags`"
      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'tag:1'"
      assert_includes sql, "'ruby'"
    end
  end

  def test_records_path_missing_raises_with_dot_notation
    json = '{"data": {"community": {}}}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "roles.json"), json)
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "roles.sql"), records_path: "data.community.roles")
      end
      assert_includes error.message, "records path 'data.community.roles'"
    end
  end

  def test_records_path_partial_match_does_not_leak_to_sibling_branch
    json = '{"data": {"wrong": {}}, "other": {"users": [{"id": "wrong"}]}}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "users.sql"), records_path: "data.users")
      end
      assert_includes error.message, "records path 'data.users'"
    end
  end

  def test_records_path_finds_correct_branch_after_unmatched_nested_sibling
    json = '{"data": {"community": {"users": [{"id": "wrong"}]}, "other": {"users": [{"id": "ok"}]}}}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      stats, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.other.users")

      assert_equal 1, stats[:rows_processed]
      assert_includes sql, "'ok'"
      refute_includes sql, "'wrong'"
    end
  end

  # ---------------------------------------------------------------------------
  # Per-file records-path config (Issue 1)
  # ---------------------------------------------------------------------------

  def test_records_path_config_routes_per_file
    users_json = '{"data": {"users": [{"id": "u:1", "login": "alice"}]}}'
    roles_json = '{"data": {"community": {"roles": [{"id": "role:1", "name": "Admin"}]}}}'
    config_yaml = <<~YAML
      users: data.users
      roles: data.community.roles
    YAML

    Dir.mktmpdir do |dir|
      write(File.join(dir, "users.json"), users_json)
      write(File.join(dir, "roles.json"), roles_json)
      config = write(File.join(dir, "paths.yml"), config_yaml)
      output = File.join(dir, "out.sql")

      stats, sql = convert(dir, output, records_path_config: config)

      assert_equal 2, stats[:files_processed]
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "CREATE TABLE `roles`"
      assert_includes sql, "'u:1'"
      assert_includes sql, "'alice'"
      assert_includes sql, "'role:1'"
      assert_includes sql, "'Admin'"
    end
  end

  def test_records_path_config_per_file_overrides_global_records_path
    # Global records_path is "data", but config maps users to "data.users"
    users_json = '{"data": {"users": [{"id": "u:1"}]}}'
    config_yaml = "users: data.users\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), users_json)
      config = write(File.join(dir, "paths.yml"), config_yaml)
      _, sql = convert(input, File.join(dir, "out.sql"), records_path: "data", records_path_config: config)

      assert_includes sql, "CREATE TABLE `users`"
      # records_path_config wins: data.users → 1 row with id
      assert_includes sql, "'u:1'"
    end
  end

  def test_records_path_config_falls_back_to_global_for_unlisted_files
    json = '{"data": [{"id": "x:1"}]}'
    config_yaml = "other: data.other\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "things.json"), json)
      config = write(File.join(dir, "paths.yml"), config_yaml)
      stats, sql = convert(input, File.join(dir, "out.sql"), records_path_config: config)

      # Not in config → falls back to default "data" detection
      assert_includes sql, "CREATE TABLE `things`"
      assert_equal 1, stats[:rows_processed]
    end
  end

  def test_records_path_config_missing_file_raises
    error = assert_raises(SiloMigrate::UsageError) do
      SiloMigrate::JSONToSQLConverter.new(records_path_config: "/nonexistent/paths.yml", verbose: false)
    end
    assert_includes error.message, "Records path config not found"
  end

  def test_records_path_config_invalid_yaml_raises
    Dir.mktmpdir do |dir|
      config = write(File.join(dir, "bad.yml"), "key: [unclosed")
      error = assert_raises(SiloMigrate::UsageError) do
        SiloMigrate::JSONToSQLConverter.new(records_path_config: config, verbose: false)
      end
      assert_includes error.message, "Could not parse records path config"
    end
  end

  def test_records_path_config_non_mapping_raises
    Dir.mktmpdir do |dir|
      config = write(File.join(dir, "bad.yml"), "- item1\n- item2\n")
      error = assert_raises(SiloMigrate::UsageError) do
        SiloMigrate::JSONToSQLConverter.new(records_path_config: config, verbose: false)
      end
      assert_includes error.message, "must be a YAML mapping"
    end
  end

  def test_invalid_records_paths_raise_usage_error
    ["", ".data", "data.", "data..users"].each do |path|
      error = assert_raises(SiloMigrate::UsageError) do
        SiloMigrate::JSONToSQLConverter.new(records_path: path, verbose: false)
      end
      assert_includes error.message, "Invalid --records-path"
    end
  end

  def test_invalid_records_path_config_value_raises_usage_error
    Dir.mktmpdir do |dir|
      config = write(File.join(dir, "bad.yml"), "users: data..users\n")
      error = assert_raises(SiloMigrate::UsageError) do
        SiloMigrate::JSONToSQLConverter.new(records_path_config: config, verbose: false)
      end
      assert_includes error.message, "Invalid records path config entry \"users\""
    end
  end

  # ---------------------------------------------------------------------------
  # End-to-end: Khoros-style GraphQL envelope (all three fixes working together)
  # ---------------------------------------------------------------------------

  def test_khoros_style_graphql_envelope_end_to_end
    # Simulates the actual Khoros/F5 DevCentral file shape:
    # data.<entity>.edges[].node with pageInfo sibling and optional cursor on edges.
    users_json = <<~JSON
      {"data": {"users": {
        "edges": [
          {"node": {"id": "user:1", "login": "alice", "email": "alice@example.com", "banned": false, "uid": 1}},
          {"node": {"id": "user:2", "login": "bob", "email": "bob@example.com", "banned": true, "uid": 2}}
        ],
        "pageInfo": {"hasNextPage": false, "endCursor": null}
      }}}
    JSON

    roles_json = <<~JSON
      {"data": {"community": {
        "roles": {
          "edges": [
            {"node": {"id": "role:t:Admin:core", "name": "Administrator", "usersCount": 13}},
            {"node": {"id": "role:t:Member:core", "name": "Member", "usersCount": 57709}}
          ],
          "pageInfo": {"hasNextPage": false, "endCursor": null}
        }
      }}}
    JSON

    config_yaml = <<~YAML
      users: data.users.edges
      roles: data.community.roles.edges
    YAML

    Dir.mktmpdir do |dir|
      write(File.join(dir, "users.json"), users_json)
      write(File.join(dir, "roles.json"), roles_json)
      config = write(File.join(dir, "paths.yml"), config_yaml)
      output = File.join(dir, "out.sql")

      stats, sql = convert(dir, output, records_path_config: config)

      assert_equal 2, stats[:files_processed]

      # Users: edges are the records; each record is {"node": {...}} —
      # node fields are flattened with node_ prefix.
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "`node_id` VARCHAR(255)"
      assert_includes sql, "`node_login` VARCHAR(255)"
      assert_includes sql, "`node_banned` TINYINT(1)"
      assert_includes sql, "`node_uid` BIGINT"
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"

      # Roles: same pattern via 3-level path
      assert_includes sql, "CREATE TABLE `roles`"
      assert_includes sql, "`node_name` VARCHAR(255)"
      assert_includes sql, "`node_users_count` BIGINT"
      assert_includes sql, "'Administrator'"
      assert_includes sql, "'Member'"
    end
  end

  # ---------------------------------------------------------------------------
  # NDJSON (newline-delimited JSON) multi-page support
  # ---------------------------------------------------------------------------

  def test_ndjson_and_jsonl_extensions_are_discovered_and_force_line_parsing
    users = "{\"id\":\"u:1\",\"login\":\"alice\"}\n{\"id\":\"u:2\",\"login\":\"bob\"}\n"
    roles = "{\"id\":\"r:1\",\"name\":\"admin\"}\n{\"id\":\"r:2\",\"name\":\"member\"}\n"
    tags = "{\"id\":\"t:1\",\"name\":\"one\"}\n{\"id\":\"t:2\",\"name\":\"two\"}\n"

    Dir.mktmpdir do |dir|
      write(File.join(dir, "users.ndjson"), users)
      gzip_write(File.join(dir, "roles.ndjson.gz"), roles)
      gzip_write(File.join(dir, "tags.jsonl.gz"), tags)

      stats, sql = convert(dir, File.join(dir, "combined.sql"))

      assert_equal 3, stats[:files_processed]
      assert_equal 6, stats[:rows_processed]
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "CREATE TABLE `roles`"
      assert_includes sql, "CREATE TABLE `tags`"
      refute_includes sql, "CREATE TABLE `users_ndjson`"
      assert_includes sql, "'alice'"
      assert_includes sql, "'admin'"
      assert_includes sql, "'one'"

      filtered_stats, filtered_sql = convert(dir, File.join(dir, "users.sql"), include_files: ["users"])
      assert_equal 1, filtered_stats[:files_processed]
      assert_equal 2, filtered_stats[:files_skipped]
      assert_includes filtered_sql, "CREATE TABLE `users`"
      refute_includes filtered_sql, "CREATE TABLE `roles`"
    end
  end

  def test_ndjson_auto_detect_two_pages
    # Two pages, each a flat {"data": [...]} document on its own line.
    page1 = '{"data": [{"id": "u:1", "login": "alice"}, {"id": "u:2", "login": "bob"}]}'
    page2 = '{"data": [{"id": "u:3", "login": "carol"}]}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"))

      assert_equal 3, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
      assert_includes sql, "'carol'"
      assert_includes sql, "CREATE TABLE `users`"
    end
  end

  def test_ndjson_explicit_flag_true
    # Same as auto-detect but with ndjson: true explicitly — must also work.
    page1 = '{"data": [{"id": "u:1", "login": "alice"}]}'
    page2 = '{"data": [{"id": "u:2", "login": "bob"}]}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), ndjson: true)

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_disabled_suppresses_line_by_line_fallback
    # With ndjson: false the input is handed directly to Oj as a single
    # document stream. This verifies the flag disables the NDJSON per-line
    # fallback path without relying on "first line only" semantics.
    page1 = '{"id": "u:1", "login": "alice"}'
    page2 = '{"id": "u:2", "login": "bob"}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.ndjson"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), ndjson: false)

      refute_equal 2, stats[:rows_processed]
      refute_includes sql, "'alice'"
    end
  end

  def test_ndjson_auto_detects_large_first_page
    big_value = "x" * 9_000
    page1 = %({"data":{"users":{"edges":[{"node":{"id":"u:1","login":"alice","bio":"#{big_value}"}}],"pageInfo":{"hasNextPage":true}}}})
    page2 = '{"data":{"users":{"edges":[{"node":{"id":"u:2","login":"bob"}}],"pageInfo":{"hasNextPage":false}}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges")

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
      assert_includes sql, "`node_bio` TEXT"
    end
  end

  def test_ndjson_object_per_line_uses_whole_line_as_record
    ndjson = "{\"id\":\"u:1\",\"login\":\"alice\"}\n{\"id\":\"u:2\",\"login\":\"bob\"}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"))

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_with_dot_notation_records_path
    # Each page uses a deeply nested records_path (same as Khoros pagination).
    page1 = '{"data":{"users":{"edges":[{"node":{"id":"u:1","login":"alice"}},{"node":{"id":"u:2","login":"bob"}}],"pageInfo":{"hasNextPage":true}}}}'
    page2 = '{"data":{"users":{"edges":[{"node":{"id":"u:3","login":"carol"}}],"pageInfo":{"hasNextPage":false}}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges")

      assert_equal 3, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
      assert_includes sql, "'carol'"
    end
  end

  def test_ndjson_with_records_path_config
    page1 = '{"data":{"users":{"edges":[{"node":{"id":"u:1","login":"alice"}}],"pageInfo":{"hasNextPage":true}}}}'
    page2 = '{"data":{"users":{"edges":[{"node":{"id":"u:2","login":"bob"}}],"pageInfo":{"hasNextPage":false}}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      write(File.join(dir, "users.ndjson"), ndjson)
      config = write(File.join(dir, "paths.yml"), "users: data.users.edges\n")
      stats, sql = convert(File.join(dir), File.join(dir, "out.sql"), records_path_config: config)

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_basename_is_used_for_schema_lookup
    page1 = '{"object_name":"users","data":[{"id":"user:1","login":"alice"}]}'
    page2 = '{"object_name":"users","data":[{"id":"user:2","login":"bob"}]}'

    Dir.mktmpdir do |dir|
      schema_dir = File.join(dir, "schema")
      write(File.join(schema_dir, "users.schema.json"), USERS_SCHEMA)
      input = write(File.join(dir, "users.ndjson"), "#{page1}\n#{page2}\n")
      stats, sql = convert(input, File.join(dir, "users.sql"), schema_dir: schema_dir)

      assert_equal 2, stats[:rows_processed]
      assert_empty stats[:warnings]
      assert_includes sql, "CREATE TABLE `users`"
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_required_records_path_missing_on_first_line_raises
    page1 = '{"data":{"users":{"items":[{"node":{"id":"u:1"}}]}}}'
    page2 = '{"data":{"users":{"edges":[{"node":{"id":"u:2"}}]}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges")
      end

      assert_includes error.message, "records path 'data.users.edges'"
      assert_includes error.message, "NDJSON line 1"
    end
  end

  def test_ndjson_required_records_path_missing_on_later_line_raises
    page1 = '{"data":{"users":{"edges":[{"node":{"id":"u:1"}}]}}}'
    page2 = '{"data":{"users":{"items":[{"node":{"id":"u:2"}}]}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges")
      end

      assert_includes error.message, "records path 'data.users.edges'"
      assert_includes error.message, "NDJSON line 2"
    end
  end

  def test_ndjson_schema_inferred_across_all_pages
    # Page 1 has "login"; page 2 adds a new column "email". Both columns must
    # appear in the inferred schema because schema inference reads all pages.
    page1 = '{"data": [{"id": "u:1", "login": "alice"}]}'
    page2 = '{"data": [{"id": "u:2", "login": "bob", "email": "bob@example.com"}]}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      _stats, sql = convert(input, File.join(dir, "users.sql"))

      assert_includes sql, "`login` VARCHAR(255)"
      assert_includes sql, "`email` VARCHAR(255)"
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob@example.com'"
    end
  end

  def test_ndjson_recover_skips_malformed_line
    page1 = '{"data": [{"id": "u:1", "login": "alice"}]}'
    bad   = '{"data": [BROKEN'
    page3 = '{"data": [{"id": "u:3", "login": "carol"}]}'
    ndjson = "#{page1}\n#{bad}\n#{page3}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), recover_truncated: true)

      # alice and carol recovered; broken page skipped
      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'carol'"
      assert_equal 1, stats[:files_recovered]
      assert_includes stats[:warnings].first, "malformed NDJSON line"
      assert_includes stats[:warnings].first, "skipped 1 line(s)"
    end
  end

  def test_ndjson_recover_raises_when_all_lines_are_malformed
    ndjson = "{\"data\": [BROKEN\n{\"data\": [ALSO_BROKEN\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)

      error = assert_raises(SiloMigrate::UsageError) do
        convert(input, File.join(dir, "users.sql"), recover_truncated: true, ndjson: true)
      end

      assert_includes error.message, "No complete records could be recovered"
      assert_includes error.message, "skipped 2 malformed line(s)"
    end
  end

  def test_ndjson_explicit_flag_true_works_with_gzip
    page1 = '{"data":{"users":{"edges":[{"node":{"id":"u:1","login":"alice"}}]}}}'
    page2 = '{"data":{"users":{"edges":[{"node":{"id":"u:2","login":"bob"}}]}}}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = gzip_write(File.join(dir, "users.json.gz"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"), records_path: "data.users.edges", ndjson: true)

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_single_line_file_not_treated_as_ndjson
    # A regular single-document JSON file on one line must not be misdetected
    # as NDJSON. Records count should equal 2 and no extra pass overhead.
    json = '{"data": [{"id": "u:1", "login": "alice"}, {"id": "u:2", "login": "bob"}]}'

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), json)
      stats, sql = convert(input, File.join(dir, "users.sql"))

      assert_equal 2, stats[:rows_processed]
      assert_includes sql, "'alice'"
      assert_includes sql, "'bob'"
    end
  end

  def test_ndjson_ordinals_are_global_across_pages
    # Ordinals passed to shredder must be globally sequential, not reset per
    # page. Verify by checking that child table _ordinal values are sequential.
    page1 = '{"data": [{"id": "u:1", "tags": [{"id": "t:1"}]}]}'
    page2 = '{"data": [{"id": "u:2", "tags": [{"id": "t:2"}]}]}'
    ndjson = "#{page1}\n#{page2}\n"

    Dir.mktmpdir do |dir|
      input = write(File.join(dir, "users.json"), ndjson)
      stats, sql = convert(input, File.join(dir, "users.sql"))

      assert_equal 2, stats[:rows_processed]
      assert_equal 2, stats[:child_rows_processed]
      # Both user rows present
      assert_includes sql, "'u:1'"
      assert_includes sql, "'u:2'"
    end
  end
end
