# frozen_string_literal: true

require "time"
require_relative "../sql_text"

module SiloMigrate
  module JSONToSQL
    # Writes MySQL/MariaDB DDL and batched INSERT statements following the
    # same conventions as the XML converter output.
    class SqlEmitter
      META_ROOT = ["_sid"].freeze
      META_CHILD = %w[_sid _parent_sid _parent_id _ordinal].freeze

      def write_header(out, source)
        out.write("-- Generated by json-to-sql converter\n")
        out.write("-- Source: #{source}\n")
        out.write("-- Generated at: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        out.write("SET NAMES utf8mb4;\nSET sql_mode = '';\nSET FOREIGN_KEY_CHECKS = 0;\nSET UNIQUE_CHECKS = 0;\n\n")
      end

      def write_footer(out)
        out.write("\nSET FOREIGN_KEY_CHECKS = 1;\nSET UNIQUE_CHECKS = 1;\n")
      end

      def write_create_table(out, name, column_defs, child:)
        lines = ["  `_sid` BIGINT NOT NULL"]
        if child
          lines << "  `_parent_sid` BIGINT NOT NULL"
          lines << "  `_parent_id` VARCHAR(255)"
          lines << "  `_ordinal` BIGINT NOT NULL"
        end
        column_defs.each do |col|
          definition = "  #{SqlText.escape_identifier(col.name)} #{col.sql_type}"
          definition += " NOT NULL" unless col.null
          definition += " COMMENT #{SqlText.escape_sql_string(col.comment)}" if col.comment
          lines << definition
        end
        lines << "  PRIMARY KEY (`_sid`)"
        if child
          lines << "  KEY `idx_parent_sid` (`_parent_sid`)"
          lines << "  KEY `idx_parent_id` (`_parent_id`)"
        end
        id_column = column_defs.find { |col| col.name == "id" }
        # TEXT-family columns cannot carry a plain KEY without a prefix length.
        lines << "  KEY `idx_id` (`id`)" if id_column && !id_column.sql_type.end_with?("TEXT")

        out.write("\n-- Table: #{name}\n")
        out.write("DROP TABLE IF EXISTS #{SqlText.escape_identifier(name)};\n")
        out.write("CREATE TABLE #{SqlText.escape_identifier(name)} (\n#{lines.join(",\n")}\n")
        out.write(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n")
      end

      def write_batch(out, name, columns, value_rows)
        return if value_rows.empty?

        identifiers = columns.map { |column| SqlText.escape_identifier(column) }
        out.write("INSERT INTO #{SqlText.escape_identifier(name)} (#{identifiers.join(', ')}) VALUES\n")
        out.write(value_rows.map { |values| "  (#{values.join(', ')})" }.join(",\n"))
        out.write(";\n")
      end

      # PII manifest derived from x-pii annotations in the JSON Schemas, so
      # downstream redaction tooling can query column sensitivity in MariaDB.
      def write_meta_table(out, rows)
        out.write("\n-- Table: _json_meta\n")
        out.write("DROP TABLE IF EXISTS `_json_meta`;\n")
        out.write(<<~SQL)
          CREATE TABLE `_json_meta` (
            `table_name` VARCHAR(64) NOT NULL,
            `column_name` VARCHAR(64) NOT NULL,
            `json_path` VARCHAR(255) NOT NULL,
            `pii` TINYINT(1) NOT NULL DEFAULT 0,
            `pii_note` TEXT,
            `source_schema` VARCHAR(255),
            PRIMARY KEY (`table_name`, `column_name`)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
        SQL
        value_rows = rows.map do |table, column, json_path, pii, note, source|
          [
            SqlText.escape_sql_string(table),
            SqlText.escape_sql_string(column),
            SqlText.escape_sql_string(json_path),
            pii.to_s,
            note.nil? ? "NULL" : SqlText.escape_sql_string(note),
            SqlText.escape_sql_string(source)
          ]
        end
        write_batch(out, "_json_meta", %w[table_name column_name json_path pii pii_note source_schema], value_rows)
      end

      def format_value(value, column_def)
        return format_null(column_def) if value.nil?
        return SqlText.escape_sql_string(value.text) if value.is_a?(JsonValue)

        case column_def&.kind
        when :boolean then value == true ? "1" : "0"
        when :integer, :float then value.is_a?(Numeric) ? value.to_s : SqlText.escape_sql_string(value.to_s)
        when :datetime then format_datetime(value)
        else SqlText.escape_sql_string(value.to_s)
        end
      end

      private

      def format_null(column_def)
        return "NULL" if column_def.nil? || column_def.null

        case column_def.kind
        when :integer, :float, :boolean then "0"
        else "''"
        end
      end

      def format_datetime(value)
        "'#{Time.iso8601(value.to_s).utc.strftime('%Y-%m-%d %H:%M:%S')}'"
      rescue ArgumentError
        SqlText.escape_sql_string(value.to_s)
      end
    end
  end
end
