# frozen_string_literal: true

require "fileutils"
require "yaml"

module SiloMigrate
  module Services
    # Generates a per-customer converter settings file whose database section
    # points at the migration DB container over the compose network (the
    # platform defaults ship with localhost, which does not resolve from
    # inside the converter container). The platform's own settings.yml is used
    # as the base so converter-specific keys are preserved.
    #
    # Output contains database credentials: it is written 0600 under
    # converter-settings/, mounted read-only into the converter container, and
    # must never be copied into AI workspaces or committed.
    class ConverterSettingsService
      CONTAINER_SETTINGS_DIR = "/converter-settings"

      README = <<~TEXT
        # Generated converter settings

        Files in this directory are generated by `silo-migrate run-converter` and
        contain database credentials for the migration containers.

        - Regenerated on each platform-shortcut run; manual edits will be lost.
        - Mounted read-only into the converter container at /converter-settings.
        - Never commit these files or copy them into AI workspaces.

        To use your own settings instead, pass `--settings PATH` to run-converter.
      TEXT

      def initialize(env: ENV, output: $stdout)
        @env = env
        @output = output
      end

      def generate(customer, platform, phase: "initial")
        config = Project.load_config(customer, @env)
        db_type, db_name, password = Project.database_config(customer, phase, config)
        project_path = Project.project_path(customer, @env)
        defaults_path = File.join(project_path, "discourse-converters", "converters", platform, "settings.yml")
        raise UsageError, "no default settings.yml for platform '#{platform}' (expected #{defaults_path})" unless File.exist?(defaults_path)

        settings = YAML.safe_load(File.read(defaults_path), aliases: true) || {}
        raise UsageError, "platform '#{platform}' settings are not a YAML mapping (#{defaults_path})" unless settings.is_a?(Hash)

        merge_connection!(
          settings,
          platform: platform,
          defaults_path: defaults_path,
          db_type: db_type,
          host: "#{customer}_#{phase}_#{db_type}",
          port: DATABASE_TYPES.fetch(db_type)[:internal_port],
          username: db_type == "postgres" ? "postgres" : "root",
          password: password,
          database: db_name
        )

        settings_dir = File.join(project_path, "converter-settings")
        FileUtils.mkdir_p(settings_dir)
        readme_path = File.join(settings_dir, "README.md")
        Project.atomic_write(readme_path, README) unless File.exist?(readme_path)

        host_path = File.join(settings_dir, "#{platform}.yml")
        Project.atomic_write(host_path, YAML.dump(settings))
        File.chmod(0o600, host_path)
        { host_path: host_path, container_path: "#{CONTAINER_SETTINGS_DIR}/#{platform}.yml" }
      end

      private

      def merge_connection!(settings, platform:, defaults_path:, db_type:, host:, port:, username:, password:, database:)
        section = settings["database"]
        unless section.is_a?(Hash)
          raise UsageError, "platform '#{platform}' settings have no 'database' section (#{defaults_path}); pass --settings with a hand-written file"
        end

        if section.key?("dataserver")
          raise UsageError, "platform '#{platform}' connects to SQL Server (dataserver), which silo-migrate does not provision; pass --settings with a hand-written file"
        end

        engine = db_type == "mariadb" ? "mysql" : db_type
        if section.key?("mysql") || section.key?("postgres")
          # Nested shape (e.g. phpbb): database.type selects an engine subsection.
          section["type"] = engine
          if engine == "postgres"
            subsection = (section["postgres"] ||= {})
            subsection.merge!("host" => host, "port" => port, "user" => username, "password" => password, "dbname" => database)
          else
            subsection = (section["mysql"] ||= {})
            subsection.merge!("host" => host, "port" => port, "username" => username, "password" => password, "database" => database)
          end
        else
          # Flat shape (vbulletin, smf, vanilla, ipboard, drupal, khoros, ...).
          section.merge!("host" => host, "port" => port, "username" => username, "password" => password, "database" => database)
        end
      end
    end
  end
end
